### ISSUE TITLE
powerlevel10k from homebrew install flagged as malware by AVG

### ISSUE THREAD

**Issue by alesniak303** [romkatv/powerlevel10k-media#5]
Perhaps a false positive, but not sure what's really going on.

During 'brew upgrade all' AVG complained about the following:

Threat name: BV:Downloader-APK [Drp]
Severity:
File name: build
File path: /private/tmp/d20221121-23832-kxbj3a/powerlevel10k-1.16.1/git
Process: /us/bin/bsdtar
Detected by: File Shield
Status: Threat blocked

Threat name: BV:Downloader-APK [Drp]
Severity:
File name: build
File path: /private/tmp/powerlevel10k-20221 121-23832-11 kfjrn/powerlevel
Process: /bin/cp
Detected by: File Shield
Status: Threat blocked

Thanks.

**Comment by romkatv** [comment]
Please report this issue to AVG.
