### ISSUE TITLE
Meslo not showing vue icon

### ISSUE THREAD

**Issue by TheGor1lla** [romkatv/powerlevel10k-media#7]
Tried using the Vue icon for my last lsd config using p10k and it's pre-patched Meslo font , but the listed vue glyphs here https://www.nerdfonts.com/cheat-sheet all don't seem to work.  

Maybe these were changed in NF 3.0?

**Comment by romkatv** [comment]
All four Vue icons are present in MesloLGS NF.

![image](https://github.com/romkatv/powerlevel10k-media/assets/1282067/7ecf1240-07ab-4180-83b7-b046087ef22e)
